[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kineo"
version = "0.1.0"
description = "Kineo: A toolkit for 3D human pose estimation"
authors = [
    { name = "Charles JAVERLIAT", email = "charles.javerliat@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "torch>=2.6.0",
    "numpy<2",
    "torchvision",
    "torchaudio",
    "moge @ git+https://github.com/microsoft/MoGe.git",
    "vggt @ git+https://github.com/facebookresearch/vggt.git",
    "aitviewer @ git+https://github.com/cjaverliat/aitviewer.git",
    "sam2 @ git+https://github.com/cjaverliat/sam2.git",
    "onnxruntime-gpu",
    "orjson",
    "kornia",
    "tqdm",
    "numpy",
    "pyglet",
    "moderngl-window==2.4.6",
    "roma",
    "opencv-python",
    "hydra-core",
    "open3d",
    "soundfile",
    "yacs",
    "spacepy",
    "rerun-sdk",
    "cv2-enumerate-cameras",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]

[project.optional-dependencies]
dev = [
    "mmpretrain",
    "mmengine",
    "mmcv @ git+https://github.com/cjaverliat/mmcv.git",
    "mmpose @ git+https://github.com/cjaverliat/mmpose.git",
    "mmdet @ git+https://github.com/cjaverliat/mmdetection.git",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["kineo*"]
